package storem;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 13 avr. 2012, 11:13:45
 */
/**
 *
 * @author Yaovi Elom Kwasi AKA REDE <ederelk@gmail.com>
 */
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import storem.credit_sales.creditSales;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.*;
import storem.databases.tableModelfunc;
import storem.products.products;
import storem.reports.reports;
import storem.sales.sales;
import storem.stock.stock;



public class mainFrame extends javax.swing.JFrame {
Icon   homeIcon =new ImageIcon(getClass().getResource("images/home/WB_Home.png")); 
Icon   allProductIcon =new ImageIcon(getClass().getResource("images/grt/structs/db.Table.16x16.png")); 
Icon   stockIcon =new ImageIcon(getClass().getResource("images/grt/structs/workbench.Document.16x16.png")); 
Icon   cart1Icon =new ImageIcon(getClass().getResource("icons/cart1.png")); 
public boolean productTabexist = false;
public boolean stockTabexist = false;
public boolean salesTabexist = false;
public boolean reportTabexist = false;
public boolean creditSalesTabexist = false;
URL url = getClass().getResource("icons/Untitled-3.jpg");
 
 java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();


    // Image myicon = getIconImages(); 
    //public static LoggedInInfo userInfo;

    /** Creates new form mainFrame */

    public mainFrame() {
        initComponents();
        setIconImage(new ImageIcon(url).getImage());
        setTitle("Store Manager");
        //setIconImage(getIconImage());
        
        
       // LookAndFeel look2 = new NimbusLookAndFeel();
       
        
        try{
            
            if(System.getProperty("os.name").contains("Windows")){
                LookAndFeel mylook =  new WindowsLookAndFeel();
                UIManager.setLookAndFeel(mylook); 
            }
           
         SwingUtilities.updateComponentTreeUI( this );
         
        }catch ( UnsupportedLookAndFeelException exception )
         {
             JOptionPane.showMessageDialog(null,exception);
        
        }
        tableModelfunc.setDBconnection();
        
         

       
      
    }

//function for setting imageIcon of frame    
/*      public   Image getFDImage() {
        java.net.URL imgURL = getClass().getResource("generic/WB_Home.jpg");
        if (imgURL != null) {
            return new ImageIcon(imgURL).getImage();
        } else {
            return null;
        }
    }*/
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        products_butt = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        close = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        home.setBackground(new java.awt.Color(255, 255, 153));
        home.setName("home"); // NOI18N
        home.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("HOME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));

        products_butt.setText("Inventaire");
        products_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                products_buttActionPerformed(evt);
            }
        });

        stock.setText("Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        jButton2.setText("Vente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Rapports");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/generic/imag2.png"))); // NOI18N

        jButton1.setText("Credits");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(147, 147, 147))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                                .addGap(923, 923, 923)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(544, 544, 544)
                        .addComponent(jLabel2)
                        .addContainerGap())))
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(products_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(products_butt)
                    .addComponent(stock)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(164, 164, 164))
        );

        jTabbedPane1.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/storem/images/home/WB_Home.png")), home); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Produits");
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Stock");
        jMenu1.add(jCheckBoxMenuItem2);

        jMenuItem1.setText("Quitter");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        close.setText("Fermer");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenuBar1.add(close);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1222)/2, (screenSize.height-603)/2, 1222, 603);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1AncestorMoved

    private void products_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_products_buttActionPerformed
        
       
         productTabexist = false;
      
       for(int i=0;i<jTabbedPane1.getTabCount();i++){
          if("Produits".equals(jTabbedPane1.getTitleAt(i)))
          {
              productTabexist = true;
              jTabbedPane1.setSelectedIndex(i);
              break;
          }
                   
       }
       if(productTabexist == false){
           
           
         // products vente = new products();
            products allProduct = new products();
             jTabbedPane1.addTab("Produits", allProduct);
             jTabbedPane1.setIconAt(jTabbedPane1.getTabCount()-1, allProductIcon);
             jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
         // TODO add your handling code here:
    }//GEN-LAST:event_products_buttActionPerformed
    }
    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
     
          stockTabexist = false;
      
       for(int i=0;i<jTabbedPane1.getTabCount();i++){
          if("Stock".equals(jTabbedPane1.getTitleAt(i)))
          {
              stockTabexist = true;
              jTabbedPane1.setSelectedIndex(i);
              break;
          }
                   
       }
       
       if(stockTabexist == false){
           
           
         // products vente = new products();
            stock allStock = new stock();
             jTabbedPane1.addTab("Stock", allStock);
             jTabbedPane1.setIconAt(jTabbedPane1.getTabCount()-1,stockIcon);
             jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
         // TODO add your handling code here:
    }                                             
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        
        if(!"Home".equals(jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex()))){
        jTabbedPane1.remove(jTabbedPane1.getSelectedIndex());
        }else{
        }// TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   reportTabexist = false;
      
       for(int i=0;i<jTabbedPane1.getTabCount();i++){
          if("Historique".equals(jTabbedPane1.getTitleAt(i)))
          {
              reportTabexist = true;
              jTabbedPane1.setSelectedIndex(i);
              break;
          }
                   
       }
       if(reportTabexist == false){
           
           
         // products vente = new products();
            reports allreports = new reports();
             jTabbedPane1.addTab("Historique", allreports);
             jTabbedPane1.setIconAt(jTabbedPane1.getTabCount()-1,stockIcon);
             jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
         // TODO add your handling code here:
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

                    salesTabexist = false;
      
       for(int i=0;i<jTabbedPane1.getTabCount();i++){
          if("Vente".equals(jTabbedPane1.getTitleAt(i)))
          {
              salesTabexist = true;
              jTabbedPane1.setSelectedIndex(i);
              break;
          }
                   
       }
       if(salesTabexist == false){
           
           
         // products vente = new products();
            sales performSales = new sales();
             jTabbedPane1.addTab("Vente", performSales);
             jTabbedPane1.setIconAt(jTabbedPane1.getTabCount()-1,cart1Icon);
             jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
         // TODO add your handling code here:
    }
      
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 creditSalesTabexist= false;
      
       for(int i=0;i<jTabbedPane1.getTabCount();i++){
          if("Credits".equals(jTabbedPane1.getTitleAt(i)))
          {
              creditSalesTabexist = true;
              jTabbedPane1.setSelectedIndex(i);
              break;
          }
                   
       }
       if(creditSalesTabexist == false){
           
           
         // products vente = new products();
           creditSales allCredits = new creditSales();
             jTabbedPane1.addTab("Credits", allCredits);
             //jTabbedPane1.setIconAt(jTabbedPane1.getTabCount()-1,cart1Icon);
             jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
         // TODO add your handling code here:
    } // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                new mainFrame().setVisible(true);
              // mainFrame newMainFrame = new mainFrame();
                
                //newMainFrame.setIconImage(Toolkit.getDefaultToolkit().getImage("WB_Home.jpg"));
               // newMainFrame.setVisible(true);
            }
        });
    }
    
    /** This method receives errors that occured and displays appropriate
     * messages.
     *
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu close;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton products_butt;
    private javax.swing.JButton stock;
    // End of variables declaration//GEN-END:variables


}
