/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * creditSales.java
 *
 * Created on 5 août 2012, 11:41:00
 */
package credit_sales;

import storem.databases.tableModelfunc;

/**
 *
 * @author Yaovi Elom Kwasi AKA REDE <ederelk@gmail.com>
 */
public class creditSales extends javax.swing.JPanel {
     public static String[] columns = {"Nom du Client","Nom du Produit","Quantité Vendue",
          "Prix Unitaire","Prix Total","Date"};
      static String  query = " SELECT customer_name,product_name,quantity_sold,unit_price,total_price,DATE_FORMAT(date,'          %d/%m/%Y    %H:%i:%s') FROM sales WHERE credit_sales=1 ";
     
      public final static  Class[] columnsType = new Class[]{ java.lang.String.class,java.lang.String.class,
    java.lang.Long.class, java.lang.Long.class,java.lang.Long.class,java.util.Calendar.class,java.util.Calendar.class};  
    

    /** Creates new form creditSales */
    public creditSales() {
        initComponents();
        tableModelfunc.setDBconnection();
        tableModelfunc.setDateLanguage("fr_FR");
        tableModelfunc.setTableModelToJtable(creditSalesTable, columns, query, columnsType);
        tableModelfunc.loadCustomer(customerNameCombo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        creditSalesTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) { return false; }};
        ;
        jPanel1 = new javax.swing.JPanel();
        customerNameCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        creditSalesTable.setAutoCreateRowSorter(true);
        creditSalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(creditSalesTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        customerNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectionner Nom Du Client" }));
        customerNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameComboActionPerformed(evt);
            }
        });

        jButton1.setText("Afficher tous les Credits");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(customerNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameComboActionPerformed
       String viewSpecificCreditQuery = query;
        
       if(!"Selectionner Nom Du Client".equals(customerNameCombo.getSelectedItem().toString())) {
           viewSpecificCreditQuery =" SELECT customer_name,product_name,quantity_sold,unit_price,"
                + "total_price,DATE_FORMAT(date,'          %d/%m/%Y    %H:%i:%s')"
                + " FROM sales WHERE credit_sales=1 AND customer_name ='"+customerNameCombo.getSelectedItem().toString()+"'";}
       
        tableModelfunc.setTableModelToJtable(creditSalesTable, columns, viewSpecificCreditQuery, columnsType);
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tableModelfunc.setTableModelToJtable(creditSalesTable, columns, query, columnsType);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable creditSalesTable;
    private javax.swing.JComboBox customerNameCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
