/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reports.java
 *
 * Created on 1 août 2012, 09:40:17
 */
package storem.reports;

import java.util.Calendar;
import storem.databases.tableModelfunc;

public class reports extends javax.swing.JPanel {

    /** Creates new form reports */
      public static String[] columns = {"Nom du Produit","Quantité Vendue",
          "Prix Unitaire","Prix Total","Date","Nom du Client"};
      java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize(); 
      static String  query = " SELECT product_name,quantity_sold,unit_price,total_price,DATE_FORMAT(date,'          %d/%m/%Y    %H:%i:%s'),customer_name FROM sales ORDER BY date DESC";
     Calendar today = Calendar.getInstance();
      public final static  Class[] columnsType = new Class[]{ java.lang.String.class,
    java.lang.Long.class, java.lang.Long.class,java.lang.Long.class,java.util.Calendar.class,java.lang.String.class};  
    
    public reports() {
        initComponents();
        tableModelfunc.setDBconnection();
        tableModelfunc.setDateLanguage("fr_FR");
        tableModelfunc.setTableModelToJtable(reportTable, columns, query, columnsType);
        tableModelfunc.loadCustomer(customerNameCombo);
        dateChooserCombo1.setSelectedDate(null);
        jLabel2.setText("Total de la journée: 0"); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) { return false; }};
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        customerNameCombo = new javax.swing.JComboBox();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        reportTable.setAutoCreateRowSorter(true);
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(reportTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Selectionner la Date des Ventes à Afficher :");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Afficher Toute L'historique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        customerNameCombo.setFont(new java.awt.Font("Tahoma", 1, 12));
        customerNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afficher les Ventes Selon le Nom Du Client" }));
        customerNameCombo.setToolTipText("");
        customerNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameComboActionPerformed(evt);
            }
        });

        dateChooserCombo1.setFormat(0);
        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12));
        dateChooserCombo1.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("Afficher les Ventes d'Aujourdhui");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Total de la journée:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/ui/search_icon.png"))); // NOI18N
        jLabel3.setText("Rechercher:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(405, 405, 405))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customerNameCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        tableModelfunc.setTableModelToJtable(reportTable, columns, query, columnsType);
        customerNameCombo.setSelectedIndex(0);
        dateChooserCombo1.setSelectedDate(null);
        jLabel2.setText("Total de la journée: 0");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameComboActionPerformed
        String viewSpecificCreditQuery = query;
        
        if(!"Afficher les Ventes Selon le Nom Du Client".equals(customerNameCombo.getSelectedItem().toString())) {
            viewSpecificCreditQuery =" SELECT product_name,quantity_sold,unit_price,"
                    + "total_price,DATE_FORMAT(date,'          %d/%m/%Y    %H:%i:%s'),customer_name"
                    + " FROM sales WHERE customer_name ='"+customerNameCombo.getSelectedItem().toString()+"'"+" ORDER BY date DESC";
            dateChooserCombo1.setSelectedDate(null);
        }
        
        tableModelfunc.setTableModelToJtable(reportTable, columns, viewSpecificCreditQuery, columnsType);
        jLabel2.setText("Total de la journée: 0");
        // TODO add your handling code here:
}//GEN-LAST:event_customerNameComboActionPerformed

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
       
         
       
       String dateHistoryQuery = "SELECT product_name,quantity_sold,unit_price,total_price,DATE_FORMAT(date,'           %d/%m/%Y    %H:%i:%s'),"
                + "customer_name FROM sales "
             + " WHERE DATE_FORMAT(date,'%Y-%m-%d')='"+String.format("%tF",dateChooserCombo1.getSelectedDate())+"'" +" ORDER BY date DESC";
        tableModelfunc.setTableModelToJtable(reportTable, columns, dateHistoryQuery, columnsType);
        String date =String.format("%tF",dateChooserCombo1.getSelectedDate());
        String sumQuery = "SELECT SUM(total_price) FROM sales WHERE DATE_FORMAT(date,'%Y-%m-%d')='"+(date==null?0:date)+"'";
        jLabel2.setText("Total de la journée: 0"); 
        jLabel2.setText("Total de la journée: "+ tableModelfunc.getSum(sumQuery));
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String dateHistoryQuery = "SELECT product_name,quantity_sold,unit_price,total_price,DATE_FORMAT(date,'           %d/%m/%Y    %H:%i:%s'),"
                + "customer_name FROM sales "
             + " WHERE DATE_FORMAT(date,'%Y-%m-%d')='"+String.format("%tF" , today )+"'" +" ORDER BY date DESC";
         String sumQuery = "SELECT SUM(total_price) FROM sales WHERE DATE_FORMAT(date,'%Y-%m-%d')='"+String.format("%tF" , today )+"'";
         customerNameCombo.setSelectedIndex(0);
         dateChooserCombo1.setSelectedDate(today);
         jLabel2.setText("Total d'Aujourdhui: 0");
         jLabel2.setText("Total d'Aujourdhui: "+ tableModelfunc.getSum(sumQuery));
          
         
        tableModelfunc.setTableModelToJtable(reportTable, columns, dateHistoryQuery, columnsType);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded

        tableModelfunc.loadCustomer(customerNameCombo);
        tableModelfunc.setTableModelToJtable(reportTable, columns, query, columnsType);     
        jLabel2.setText("Total de la journée: 0"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchCaretUpdate

        if(!search.getText().equals(""))
            tableModelfunc.searchSales(search, reportTable, columns);
        else
            tableModelfunc.setTableModelToJtable(reportTable, columns, query, columnsType);
    }//GEN-LAST:event_searchCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox customerNameCombo;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportTable;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
