/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sales.java
 *
 * Created on 30 avr. 2012, 16:25:21
 */
package storem.sales;


import com.mysql.jdbc.JDBC4CallableStatement;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Event;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.Calendar;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.LookAndFeel;
import javax.swing.table.DefaultTableModel;
import storem.databases.tableModelfunc;

/**
 *
 * @author Yaovi Elom Kwasi AKA REDE <ederelk@gmail.com>
 */
public class sales extends javax.swing.JPanel {

    public final static String[] columns = {"Nom du Produit","Stock"};
    public final static String[] columnNames = {"Nom du Produit","Quantité","Prix Unitaire","Prix Total"};
     public final static  Class[] columnsType = new Class[]{ java.lang.String.class, java.lang.Long.class};
     String query = " SELECT product_name,left_in_stock FROM stocks where left_in_stock > 0";
      Calendar today = Calendar.getInstance();
      DefaultTableModel defaultTable = new DefaultTableModel(columnNames,0);
      int total = 0,originalTotalValue = 0;
  java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize(); 
  javax.swing.Timer animTimer = new javax.swing.Timer(1000, null );
  Icon   invertArrowIcon =new ImageIcon(getClass().getResource("arrowinvert.png")); 
  //java.net.URL helpURL = sales.class.getResource("TextSamplerDemoHelp.html");
  static final String  RECIEPT_HEADER ="<html > "
          
          + "<head></head><body  ><div id=\"header\">"
          + "<table  border =\"0\"  cellspacing=\"0\" cellpadding=\"0\"   ><tr>"
          + "<td style=\"font-size:20px;\"><strong>Ets. SOPHIASON</strong></td>"
          + "</tr> <tr"
          + "<td style=\"margin-top:0px;font-size:10px;\"> ALIMENTATION GENERALE &amp; DIVERS</td>"
          + "</tr> <tr>"
          + " <td style=\"margin-top:0px;font-size:10px;\" >Rue du Haho BP:2320 Cel: 99478696</td>"
          + "</tr> <tr><td style=\"margin-top:0px;font-size:10px;\">lomé-Togo</td>"
          + "</tr></table></div> </br>&nbsp";
  static  final String RECEIPT_CLIENT_NAME = "<div ><table><tr><td>Nom du Client : <a href=\"\">";
  static  final String RECEIPT_BODY ="</a></td></tr></table>  </div><div >"
          + "<table  border =\"1\"  cellspacing=\"0\" style=\"margin-top:8px;float:left;\"  ><caption ></caption>"
          + "<tr><th >QTE</th><th>DESIGNATION</th><th>P.U.</th><th>P.T.</th> </tr>";
   static  final String RECEIPT_TOTAL ="<tr><td style=\"border:none;\"></td>"
           + "<td style=\"border:none;\"> </td> <th  rowspan=\"2\" class=\"center\">TOTAL    </th>"
           + "<th>";
   static  final String RECEIPT_DATE ="</th> </tr> </table> &nbsp&nbsp</div> "
           + "<div><table><tr><td  >Date : "; 
          
    static  final String RECEIPT_FOOTER =  "</td><td>.....</td> <td>Signature : ......................</td> </tr> </table></div></body></html>";
    /** Creates new form sales */
    public sales() {
        initComponents();
        tableModelfunc.setDBconnection();
        tableModelfunc.setDateLanguage("fr_FR");
       
        //edit.setMnemonic(KeyEvent.VK_ALT);
       // selectSales.setMnemonic(KeyEvent.VK_ENTER);
        
        
        //deleteFromReciet.setMnemonic(KeyEvent.VK_DELETE);
        putClientProperty("receiptTable.autoStartsEdit", Boolean.FALSE);
        System.err.println(getClientProperty("receiptTable.autoStartsEdit"));
        System.err.println(getClientProperty("edit.Mnemonic"));
        tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);
        tableModelfunc.loadCustomer(customerName);
     /*   try {
            jEditorPane1.setPage(helpURL);
            
        } catch (IOException ex) {
            Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        //date.setText(String.format( "%1$tA %1$td ,%1$tB %1$tY\n", today ));
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityDialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        quantityCombo = new javax.swing.JComboBox();
        cancel = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        endOfTransactions1 = new javax.swing.JCheckBox();
        jlabelll = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jlabelll1 = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        newCustomerDialog = new javax.swing.JDialog();
        customeNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        validateTransaction = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button5 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        amountTendered = new javax.swing.JTextField();
        PrintReceiptDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiptTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            { return false; }
        };
        jPanel1 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comfirmSales = new javax.swing.JButton();
        creditSales = new javax.swing.JCheckBox();
        customerName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        addCustomer = new javax.swing.JButton();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int column)
            { return false; }

        };
        selectSales = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        endOfTransactions = new javax.swing.JCheckBox();
        deleteFromReciet = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();

        quantityDialog.setSize(300, 240);
        quantityDialog.setAlwaysOnTop(true);
        quantityDialog.setResizable(false);
        quantityDialog.setLocation((screenSize.width-quantityDialog.getWidth())/2, (screenSize.height-quantityDialog.getHeight())/2);
        quantityDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityDialogKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityDialogKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Quantité:");

        quantityCombo.setFont(new java.awt.Font("Tahoma", 0, 14));
        quantityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboActionPerformed(evt);
            }
        });
        quantityCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityComboKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityComboKeyTyped(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/ui/DiscardRed.png"))); // NOI18N
        cancel.setText("Annuler");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 0, 14));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/ui/ApplyGreen.png"))); // NOI18N
        edit.setText("Enregistrer");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        endOfTransactions1.setFont(new java.awt.Font("Tahoma", 0, 14));
        endOfTransactions1.setText("Fin de Transaction");
        endOfTransactions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endOfTransactions1ActionPerformed(evt);
            }
        });
        endOfTransactions1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                endOfTransactions1KeyPressed(evt);
            }
        });

        jlabelll.setFont(new java.awt.Font("Tahoma", 1, 14));
        jlabelll.setText("Prix Unitaire:");

        price.setFont(new java.awt.Font("Tahoma", 1, 14));
        price.setText("jLabel2");

        jlabelll1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jlabelll1.setText("Stock:");

        stock.setFont(new java.awt.Font("Tahoma", 1, 14));
        stock.setText("Jlabel2");

        javax.swing.GroupLayout quantityDialogLayout = new javax.swing.GroupLayout(quantityDialog.getContentPane());
        quantityDialog.getContentPane().setLayout(quantityDialogLayout);
        quantityDialogLayout.setHorizontalGroup(
            quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quantityDialogLayout.createSequentialGroup()
                        .addComponent(jlabelll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quantityDialogLayout.createSequentialGroup()
                        .addComponent(cancel)
                        .addGap(59, 59, 59)
                        .addComponent(edit))
                    .addGroup(quantityDialogLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelll1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endOfTransactions1)
                            .addComponent(stock))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        quantityDialogLayout.setVerticalGroup(
            quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelll)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelll1)
                    .addComponent(stock))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(endOfTransactions1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(quantityDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        newCustomerDialog.setTitle("Nouveau Client");
        newCustomerDialog.setSize(370,  110);
        newCustomerDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        newCustomerDialog.setAlwaysOnTop(true);
        newCustomerDialog.setResizable(false);
        newCustomerDialog.setLocation((screenSize.width-newCustomerDialog.getWidth())/2, (screenSize.height-newCustomerDialog.getHeight())/2);

        customeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeNameFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Nom Du client:");

        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newCustomerDialogLayout = new javax.swing.GroupLayout(newCustomerDialog.getContentPane());
        newCustomerDialog.getContentPane().setLayout(newCustomerDialogLayout);
        newCustomerDialogLayout.setHorizontalGroup(
            newCustomerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCustomerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addGroup(newCustomerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newCustomerDialogLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8))
                    .addComponent(customeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        newCustomerDialogLayout.setVerticalGroup(
            newCustomerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCustomerDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(newCustomerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(newCustomerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        validateTransaction.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        validateTransaction.setTitle("Valider Transaction");
        validateTransaction.setAlwaysOnTop(true);
        validateTransaction.setSize(635, 365);
        validateTransaction.setResizable(false);
        validateTransaction.setLocation((screenSize.width-validateTransaction.getWidth())/2, (screenSize.height-validateTransaction.getHeight())/2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(4, 3, 3, 4));

        button1.setFont(new java.awt.Font("Dialog", 1, 36));
        button1.setLabel("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1);

        button2.setFont(new java.awt.Font("Dialog", 1, 36));
        button2.setLabel("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel3.add(button2);

        button3.setFont(new java.awt.Font("Dialog", 1, 36));
        button3.setLabel("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel3.add(button3);

        button4.setFont(new java.awt.Font("Dialog", 1, 36));
        button4.setLabel("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel3.add(button4);

        button6.setFont(new java.awt.Font("Dialog", 1, 36));
        button6.setLabel("5");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel3.add(button6);

        button7.setFont(new java.awt.Font("Dialog", 1, 36));
        button7.setLabel("6");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel3.add(button7);

        button5.setFont(new java.awt.Font("Dialog", 1, 36));
        button5.setLabel("7");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel3.add(button5);

        button8.setFont(new java.awt.Font("Dialog", 1, 36));
        button8.setLabel("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel3.add(button8);

        button9.setFont(new java.awt.Font("Dialog", 1, 36));
        button9.setLabel("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel3.add(button9);

        button10.setFont(new java.awt.Font("Dialog", 1, 36));
        button10.setLabel("0");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel3.add(button10);

        button11.setFont(new java.awt.Font("Dialog", 1, 36));
        button11.setLabel("<");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        jPanel3.add(button11);

        button12.setFont(new java.awt.Font("Dialog", 1, 36));
        button12.setLabel("CE");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        jPanel3.add(button12);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Total à Payer:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Motant  Du Client: ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setText("Monnaie:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel16.setText("0");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);

        amountTendered.setFont(new java.awt.Font("Tahoma", 1, 18));
        amountTendered.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                amountTenderedCaretUpdate(evt);
            }
        });
        amountTendered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTenderedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amountTendered, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(amountTendered, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout validateTransactionLayout = new javax.swing.GroupLayout(validateTransaction.getContentPane());
        validateTransaction.getContentPane().setLayout(validateTransactionLayout);
        validateTransactionLayout.setHorizontalGroup(
            validateTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, validateTransactionLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        validateTransactionLayout.setVerticalGroup(
            validateTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PrintReceiptDialog.setTitle("Detailles du Produit en Stock");
        PrintReceiptDialog.setResizable(false);
        PrintReceiptDialog.setSize(500, 650);

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jScrollPane3.setViewportView(jEditorPane1);

        PrintReceiptDialog.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reçu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(102, 102, 255))); // NOI18N

        receiptTable.getTableHeader().setReorderingAllowed(false);
        receiptTable.setBackground(new java.awt.Color(255, 255, 102));
        receiptTable.setFont(new java.awt.Font("Tahoma", 0, 14));
        receiptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom du Produit", "Quantité", "Prix Unitaire", "Prix Total"
            }
        ));
        receiptTable.setFocusable(false);
        receiptTable.setRowHeight(20);
        receiptTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                receiptTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(receiptTable);

        totalLabel.setBackground(new java.awt.Color(102, 102, 255));
        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        totalLabel.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("  Prix Total: ");
        jLabel4.setOpaque(true);

        comfirmSales.setFont(new java.awt.Font("Tahoma", 0, 14));
        comfirmSales.setText("Valider la Vente");
        comfirmSales.setEnabled(false);
        comfirmSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmSalesActionPerformed(evt);
            }
        });

        creditSales.setFont(new java.awt.Font("Tahoma", 0, 14));
        creditSales.setText("Vente à CREDIT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(creditSales, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comfirmSales, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditSales)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comfirmSales, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        customerName.setBackground(new java.awt.Color(153, 204, 255));
        customerName.setFont(new java.awt.Font("Tahoma", 0, 14));
        customerName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inconnu" }));
        customerName.setOpaque(false);
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Nom du Client :");

        addCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/ui/collapsing_panel_header_tab_add2.png"))); // NOI18N
        addCustomer.setToolTipText("Ajouter Nouveau Client");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });

        inventoryScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produits Disponible", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        inventoryTable.getTableHeader().setReorderingAllowed(false);
        inventoryTable.setFont(new java.awt.Font("Tahoma", 0, 14));
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom du Produit", "Code du Produit"
            }
        ));
        inventoryTable.setFocusable(false);
        inventoryTable.setRowHeight(20);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        inventoryTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inventoryTableKeyPressed(evt);
            }
        });
        inventoryScrollPane.setViewportView(inventoryTable);

        selectSales.setBackground(new java.awt.Color(153, 204, 255));
        selectSales.setFont(new java.awt.Font("Tahoma", 0, 14));
        selectSales.setText("Selectionner");
        selectSales.setBorder(null);
        selectSales.setBorderPainted(false);
        selectSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSalesActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 0, 14));
        search.requestFocusInWindow();
        search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchCaretUpdate(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/ui/search_icon.png"))); // NOI18N
        jLabel5.setText("Rechercher:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        endOfTransactions.setFont(new java.awt.Font("Tahoma", 0, 14));
        endOfTransactions.setText("Fin de Transaction");
        endOfTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endOfTransactionsActionPerformed(evt);
            }
        });

        deleteFromReciet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/icons/tiny_cancel.png"))); // NOI18N
        deleteFromReciet.setText("Supprimer du Reçu");
        deleteFromReciet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFromRecietActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/icons/arrowinvert.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/icons/arrowinvert.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/icons/arrowinvert.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/icons/arrowinvert.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/icons/arrowinvert.png"))); // NOI18N

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storem/images/icons/tiny_refresh.png"))); // NOI18N
        refresh.setText("Actualiser");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(deleteFromReciet, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(endOfTransactions)
                                .addComponent(selectSales, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inventoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel12)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel11)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel10)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(deleteFromReciet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refresh)
                                .addGap(18, 18, 18)))
                        .addComponent(inventoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(selectSales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(endOfTransactions)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void selectSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSalesActionPerformed

        try {
                 quantityDialog.setTitle(inventoryTable.getValueAt(inventoryTable.getSelectedRow(),inventoryTable.getColumnCount()-2).toString());
                 tableModelfunc.loadSelectedProductPrice(inventoryTable.getValueAt(inventoryTable.getSelectedRow(),0).toString(), price);
                  tableModelfunc.loadSelectedProductStock(inventoryTable.getValueAt(inventoryTable.getSelectedRow(),0).toString(), stock);
                 quantityCombo.removeAllItems();
                 if(Integer.parseInt(stock.getText())<=0){
                     quantityCombo.addItem(0);
                 }else{
                  for(int i=1;i<=Integer.parseInt(stock.getText());i++){
                     quantityCombo.addItem(i);
                 }
                 }
                  quantityCombo.setSelectedIndex(0);
                 endOfTransactions1.setSelected(false);
                 quantityDialog.setModal(true);
                 quantityDialog.setVisible(true);
                 edit.requestFocusInWindow();
                 
            
        } catch (Exception e) {
            quantityDialog.dispose();
            quantityDialog.setModal(false);
            JOptionPane.showMessageDialog(null, "S'il vous plais selectionnez un"
                    + " produit disponible avant de cliquer sur le boutton Selectioner", "Erreur", 0);
        }
        
               
        
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSalesActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

       quantityDialog.dispose();
       quantityDialog.setModal(false);
        // TODO add your handling code here:
}//GEN-LAST:event_cancelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        boolean exist = false;
        if(Integer.parseInt(stock.getText())<=0){
    JOptionPane.showMessageDialog(this, "Ce produit est fini du Stock. Vous ne pouvez pas effectuer cette operation!", "Attention!",JOptionPane.INFORMATION_MESSAGE );
    quantityDialog.dispose();
    quantityDialog.setModal(false);
}else{
            for(int i =0;i< receiptTable.getRowCount();i++){
                if(String.valueOf(receiptTable.getValueAt(i,0)).equals(quantityDialog.getTitle()) && 
                  String.valueOf(receiptTable.getValueAt(i,2)).equals(price.getText())  ){
                    total -= Integer.parseInt(receiptTable.getValueAt(i,3).toString());
                    receiptTable.setValueAt((Integer.parseInt(quantityCombo.getSelectedItem().toString())), i, 1);
                    
                    receiptTable.setValueAt(((Integer.parseInt(quantityCombo.getSelectedItem().toString())* Integer.parseInt(price.getText()))), i, 3);
                    total += Integer.parseInt(quantityCombo.getSelectedItem().toString())* Integer.parseInt(price.getText());
                    exist = true;
                    break;
                }
            }
            if(!exist){
       total += Integer.parseInt(tableModelfunc.setPurchaseToCart(inventoryTable.getValueAt(inventoryTable.getSelectedRow(), 0).toString(), 
                receiptTable, columnNames, defaultTable, quantityCombo));}
            
        search.setText("");
        search.requestFocusInWindow();
       
        //search.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        totalLabel.setText(Integer.toString(total));
        quantityDialog.dispose();
        quantityDialog.setModal(true);}
        // TODO add your handling code here:
}//GEN-LAST:event_editActionPerformed

    private void comfirmSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmSalesActionPerformed

     
      if(creditSales.isSelected()){
        if(customerName.getSelectedIndex()<=0){
            JOptionPane.showMessageDialog(this, "S'il vous plait ,veuillez specifier le nom de client qui achete à credit", "Erreur", JOptionPane.ERROR_MESSAGE);
        }  else{
            jLabel15.setText(totalLabel.getText());
        jLabel16.setText("0");
        amountTendered.setText("");
        validateTransaction.setModal(true);
        validateTransaction.setVisible(true);
        }
      }
      if(!creditSales.isSelected()){
          jLabel15.setText(totalLabel.getText());
        jLabel16.setText("0");
        amountTendered.setText("");
        validateTransaction.setVisible(true);
      }
        
        
        
    
      /*  if(decision == JOptionPane.NO_OPTION){
             receiptTable.setModel(defaultTable);
        }*/
        
        // TODO add your handling code here:
    }//GEN-LAST:event_comfirmSalesActionPerformed

    private void searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchCaretUpdate

         if(!search.getText().equals("")){
            //tableModelfunc.searchProductsInventory(search, inventoryTable, columns);
            tableModelfunc.searchStocksAvailable(search, inventoryTable, columns);
            inventoryTable.changeSelection(0, inventoryTable.getRowCount(), false,false );  
         }
         else{
            tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);
                              
         }// TODO add your handling code here:
    }//GEN-LAST:event_searchCaretUpdate

    private void endOfTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endOfTransactionsActionPerformed

        
        if(endOfTransactions.isSelected()){
               
        //applyDiscount.setEnabled(true);
        //discountField.setEnabled(true);
        comfirmSales.setEnabled(true);
        selectSales.setEnabled(false);
        inventoryTable.setBackground(Color.GRAY);
        
        }else{
            selectSales.setEnabled(false);
        // applyDiscount.setEnabled(false);
        // applyDiscount.setSelected(false);
        comfirmSales.setEnabled(false); 
        selectSales.setEnabled(true);
       // discountField.setEnabled(false);
       // discountField.setText("");
        inventoryTable.setBackground(Color.WHITE);
        
        int localTotal = 0;
            for(int count = 0;count<receiptTable.getRowCount();count++)
                    localTotal+=Integer.parseInt(receiptTable.getValueAt(count, receiptTable.getColumnCount()-1).toString());
               totalLabel.setText(Integer.toString(localTotal));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_endOfTransactionsActionPerformed

    private void deleteFromRecietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFromRecietActionPerformed

        try {
             int removedValue = Integer.parseInt(receiptTable.getValueAt(receiptTable.getSelectedRow(), receiptTable.getColumnCount()-1).toString());
        defaultTable.removeRow(receiptTable.getSelectedRow());
        total -=removedValue;
        totalLabel.setText(Integer.toString(total));
        receiptTable.setModel(defaultTable);
//        discountField.setText("");
       // applyDiscount.setSelected(false);
        receiptTable.changeSelection(receiptTable.getRowCount()-1, receiptTable.getSelectedColumn(), false,false );                   
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "S'il vous plais selectionnez un element du"
                    + " Reçu  avant de cliquer sur le boutton Supprimer", "Erreur", 0);
        }
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFromRecietActionPerformed

    private void receiptTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiptTableKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_DELETE ){
            int removedValue = Integer.parseInt(receiptTable.getValueAt(receiptTable.getSelectedRow(), receiptTable.getSelectedColumn()).toString());
            defaultTable.removeRow(receiptTable.getSelectedRow());
            total -= removedValue;
            totalLabel.setText(Integer.toString(total));
            receiptTable.setModel(defaultTable);
            
        }
        // TODO add your handling code here:
}//GEN-LAST:event_receiptTableKeyPressed

    private void endOfTransactions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endOfTransactions1ActionPerformed
       
        if(endOfTransactions1.isSelected()){
      //  applyDiscount.setEnabled(true);
      //  discountField.setEnabled(true);
        comfirmSales.setEnabled(true);
        selectSales.setEnabled(false);
        endOfTransactions.setSelected(true);
        inventoryTable.setBackground(Color.GRAY);
        }else{
       //  applyDiscount.setEnabled(false);
        // discountField.setEnabled(false);
        comfirmSales.setEnabled(false); 
        selectSales.setEnabled(true);
        endOfTransactions.setSelected(false);
        inventoryTable.setBackground(Color.white);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_endOfTransactions1ActionPerformed

    private void quantityDialogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityDialogKeyTyped

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityDialogKeyTyped

    private void quantityDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityDialogKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        edit.doClick();
       // TODO add your handling code here:
    }//GEN-LAST:event_quantityDialogKeyPressed

    private void quantityComboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityComboKeyTyped

         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        edit.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_quantityComboKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

       // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed

        newCustomerDialog.setModal(true);
        newCustomerDialog.setVisible(true);
        customeNameField.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        newCustomerDialog.dispose();
        newCustomerDialog.setModal(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void customeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeNameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String insertQuery ="INSERT INTO customers VALUES(NULL,'"+customeNameField.getText()+"')";
        
        if(tableModelfunc.executeQueryUpdate(insertQuery)){
        customerName.addItem(customeNameField.getText());
        customerName.setSelectedItem(customeNameField.getText());
        newCustomerDialog.dispose();}else{
             JOptionPane.showMessageDialog(this, " Ce nom existe déjà . Veuillez le selectionner", "Erreur", JOptionPane.ERROR_MESSAGE);
            newCustomerDialog.dispose();
            newCustomerDialog.setModal(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked

        
        if(evt.getClickCount() == 2){
         selectSales.doClick();   
        }// TODO add your handling code here:
    }//GEN-LAST:event_inventoryTableMouseClicked

    private void inventoryTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inventoryTableKeyPressed

        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
             total += Integer.parseInt(tableModelfunc.setPurchaseToCart(inventoryTable.getValueAt(inventoryTable.getSelectedRow(), inventoryTable.getColumnCount()-1).toString(), 
                receiptTable, columnNames, defaultTable, quantityCombo));
        search.setText("");
        search.requestFocusInWindow();
       
        //search.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        totalLabel.setText(Integer.toString(total));
       // quantityDialog.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryTableKeyPressed

    private void quantityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityComboActionPerformed

    private void quantityComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityComboKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            edit.doClick();
                // TODO add your handling code here:
    }//GEN-LAST:event_quantityComboKeyPressed

    private void endOfTransactions1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_endOfTransactions1KeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            edit.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_endOfTransactions1KeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button1.getLabel());
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button2.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button3.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button6.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button9.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button4.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button7.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button5.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button8.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText(amountTendered.getText()+button10.getLabel());        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed

        amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet()&&!amountTendered.getText().isEmpty())
           amountTendered.setText(amountTendered.getText().substring(0, amountTendered.getText().length()-1));        // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed

        amountTendered.requestFocusInWindow();
        if(amountTendered.isCursorSet())
            amountTendered.setText("");    
jLabel16.setText("0");
// TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   
        validateTransaction.dispose();
        validateTransaction.setModal(false);
       int decision = JOptionPane.showConfirmDialog(this, "Voulez vous imprimer le reçu?", "Imprimer Reçu", JOptionPane.YES_NO_OPTION,3 ) ;
       
        if (decision == JOptionPane.YES_OPTION){
            String ReceiptMain = "";
             String insertQuery = "";
             String UpdateQuery = "";
            // validateTransaction.dispose();
        for(int row = 0;row<receiptTable.getRowCount();row++){
             
            insertQuery = "INSERT INTO sales VALUES( NULL,'"+
              receiptTable.getValueAt(row,0) +"','"+receiptTable.getValueAt(row,1)
                    +"',"+receiptTable.getValueAt(row,2)+ ","+receiptTable.getValueAt(row,3)+",'"
                   +customerName.getSelectedItem().toString() + "',NULL,'"+(creditSales.isSelected()?"CREDIT":"PAYER")+"','"+(creditSales.isSelected()?"EN ATTENTE":"PAYEMENT EFFECTUE LE MEMEJOUR")+"',"+(creditSales.isSelected()?0:1)+")";
            UpdateQuery = "UPDATE stocks SET left_in_stock =left_in_stock-"+
                    receiptTable.getValueAt(row,1)+" WHERE product_name = '"+receiptTable.getValueAt(row,0) +"'";
            ReceiptMain +=  "<tr> <td>"+receiptTable.getValueAt(row,1)+"</td>"
            + "<td >"+receiptTable.getValueAt(row,0)+"</td>"
                    + " <td class=\"center\">"+receiptTable.getValueAt(row,2)+"</td>"
                    + "<td class=\"center\">"+receiptTable.getValueAt(row,3)+"</td></tr>";
  
            tableModelfunc.executeQueryUpdate(insertQuery);
            tableModelfunc.executeQueryUpdate(UpdateQuery);
        }
        jEditorPane1.setText(RECIEPT_HEADER+RECEIPT_CLIENT_NAME+customerName.getSelectedItem().toString() +RECEIPT_BODY+ReceiptMain+RECEIPT_TOTAL+
                totalLabel.getText()+RECEIPT_DATE+String.format( "%1$td/%1$tm/%1$tY", today )+RECEIPT_FOOTER);
        
        
                PrintReceiptDialog.setVisible(true);
            try {
                jEditorPane1.print();
                    tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);
                
            } catch (PrinterException ex) {
                Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
            }
            PrintReceiptDialog.dispose();
            //PrintReceiptDialog.setModal(false);
                ReceiptMain = "";
                 endOfTransactions.setSelected(false);
        selectSales.setEnabled(true);
//        applyDiscount.setEnabled(false);
  //      discountField.setEnabled(false);
    //    applyDiscount.setSelected(false);
        comfirmSales.setEnabled(false);
      //  discountField.setText("");
        defaultTable.setRowCount(0);
      
        total = 0;
        totalLabel.setText(Integer.toString(total));
       receiptTable.setModel(defaultTable);
       inventoryTable.setBackground(Color.WHITE);
        
           }
            if(decision == JOptionPane.NO_OPTION){
                
                PrintReceiptDialog.dispose();
                PrintReceiptDialog.setModal(false);
              //  validateTransaction.dispose();
                 String insertQuery = "";
                 String UpdateQuery = "";
        for(int row = 0;row<receiptTable.getRowCount();row++){
             
            insertQuery = "INSERT INTO sales VALUES( NULL,'"+
              receiptTable.getValueAt(row,0) +"','"+receiptTable.getValueAt(row,1)
                    +"',"+receiptTable.getValueAt(row,2)+ ","+receiptTable.getValueAt(row,3)+",'"
                   +customerName.getSelectedItem().toString() + "',NULL,'"+(creditSales.isSelected()?"CREDIT":"PAYER")+"','"+(creditSales.isSelected()?"EN ATTENTE":"PAYEMENT EFFECTUE LE MEME JOUR")+"',"+(creditSales.isSelected()?0:1)+" )";
             UpdateQuery = "UPDATE stocks SET left_in_stock =left_in_stock-"+
                    receiptTable.getValueAt(row,1)+" WHERE product_name = '"+receiptTable.getValueAt(row,0) +"'";
            tableModelfunc.executeQueryUpdate(insertQuery);
            tableModelfunc.executeQueryUpdate(UpdateQuery);
            
        }
                endOfTransactions.setSelected(false);
        selectSales.setEnabled(true);
//        applyDiscount.setEnabled(false);
  //      discountField.setEnabled(false);
    //    applyDiscount.setSelected(false);
        comfirmSales.setEnabled(false);
      //  discountField.setText("");
        defaultTable.setRowCount(0);
      
        total = 0;
        totalLabel.setText(Integer.toString(total));
       receiptTable.setModel(defaultTable);
       inventoryTable.setBackground(Color.WHITE);
       tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);
            }
           // receiptTable.setModel(defaultTable); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
validateTransaction.dispose();
   validateTransaction.setModal(false);     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void amountTenderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTenderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTenderedActionPerformed

    private void amountTenderedCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_amountTenderedCaretUpdate

        if(!"".equals(amountTendered.getText())){
       if(Integer.parseInt( amountTendered.getText())>= Integer.parseInt(jLabel15.getText())){
           jLabel16.setText(String.valueOf(Integer.parseInt( amountTendered.getText())-Integer.parseInt(jLabel15.getText())));
        }
        if (Integer.parseInt( amountTendered.getText())< Integer.parseInt(jLabel15.getText())){
            jLabel16.setText("0");
        }
       
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTenderedCaretUpdate

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

        inventoryTable.setModel(defaultTable);
        tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded

        tableModelfunc.loadCustomer(customerName);
        inventoryTable.setModel(defaultTable);
        tableModelfunc.setTableModelToJtable(inventoryTable, columns, query, columnsType);        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PrintReceiptDialog;
    private javax.swing.JButton addCustomer;
    private javax.swing.JTextField amountTendered;
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JButton cancel;
    private javax.swing.JButton comfirmSales;
    private javax.swing.JCheckBox creditSales;
    private javax.swing.JTextField customeNameField;
    private javax.swing.JComboBox customerName;
    private javax.swing.JButton deleteFromReciet;
    private javax.swing.JButton edit;
    private javax.swing.JCheckBox endOfTransactions;
    private javax.swing.JCheckBox endOfTransactions1;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabelll;
    private javax.swing.JLabel jlabelll1;
    private javax.swing.JDialog newCustomerDialog;
    private javax.swing.JLabel price;
    private javax.swing.JComboBox quantityCombo;
    private javax.swing.JDialog quantityDialog;
    private javax.swing.JTable receiptTable;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField search;
    private javax.swing.JButton selectSales;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JDialog validateTransaction;
    // End of variables declaration//GEN-END:variables
}
